export enum DeviceEmitterEvents {
  APP_INIT_COMPLETED = 'APP_INIT_COMPLETED',
  DOSH_INITIALIZED = 'DOSH_INITIALIZED',
  GIFT_CARD_REDEEMED = 'GIFT_CARD_REDEEMED',
  WALLET_LOAD_HISTORY = 'WALLET_LOAD_HISTORY',
  PUSH_NOTIFICATIONS = 'PUSH_NOTIFICATIONS',
}
